(function(){"use strict";
var docs=Array.isArray(window.EF_CRUX_DOCS)?window.EF_CRUX_DOCS:[];
var params=new URLSearchParams(location.search),id=params.get('id'),doc=docs.find(function(x){return x.id===id});
if(!doc){document.getElementById('title').textContent='Document not found';return}
function isCompactReader(){var coarse=!!(window.matchMedia&&window.matchMedia('(hover:none) and (pointer:coarse)').matches),w=window.innerWidth||document.documentElement.clientWidth||0,h=window.innerHeight||document.documentElement.clientHeight||0,shortSide=Math.min(w,h),longSide=Math.max(w,h);return !!(window.matchMedia&&(window.matchMedia('(max-width:820px)').matches||(coarse&&shortSide<=1024&&longSide<=1400)))}
var mobileReader=isCompactReader(),isTrick=doc.kind==='tricks',isBookCrux=doc.kind==='crux',isEconomicsCrux=isBookCrux&&doc.subject==='Economics',isAdvanceMaths=doc.id==='ct0468'||doc.sourceTitle==='Advance Maths Formula Book';
if(isTrick)document.documentElement.classList.add('efp-trick-pdf');
if(isBookCrux)document.documentElement.classList.add('efp-book-crux-pdf');
if(isEconomicsCrux)document.documentElement.classList.add('efp-economics-crux-pdf');
if(isAdvanceMaths)document.documentElement.classList.add('efp-advance-maths-dark-pdf');
var page=Math.max(1,Math.min(doc.pages,parseInt(params.get('page')||'1',10)||1));
var pages=[],pdfDoc=null,renderTask=null,zoom=mobileReader?1.10:1,autoFit=true,lastPageLandscape=false,lastDevicePortrait=window.innerHeight>=window.innerWidth;
var title=document.getElementById('title'),crumb=document.getElementById('crumb'),input=document.getElementById('pageInput'),total=document.getElementById('pageTotal'),favBtn=document.getElementById('favBtn'),bookmarkPage=document.getElementById('bookmarkPage'),completeBtn=document.getElementById('completeBtn'),resetProgressBtn=document.getElementById('resetProgressBtn'),openPdf=document.getElementById('openPdf'),openPdf2=document.getElementById('openPdf2'),docSearch=document.getElementById('docSearch'),docHits=document.getElementById('docHits'),pdfStage=document.getElementById('pdfStage'),pdfCanvas=document.getElementById('pdfCanvas'),pdfLoading=document.getElementById('pdfLoading'),pdfError=document.getElementById('pdfError'),zoomLabel=document.getElementById('zoomLabel');
var clarityStyle=document.createElement('style');clarityStyle.id='efp-pdf-clarity-profile';clarityStyle.textContent='html.dark.efp-book-crux-pdf #pdfCanvas{filter:invert(.95) hue-rotate(180deg) saturate(1.04) brightness(1.10) contrast(1.18)!important;background:#080d15!important}html.dark.efp-book-crux-pdf .pdf-stage{background:#040911!important}html.dark.efp-economics-crux-pdf #pdfCanvas{filter:invert(.965) hue-rotate(180deg) saturate(1.08) brightness(1.12) contrast(1.22)!important;background:#060b12!important}html.dark.efp-economics-crux-pdf .pdf-stage{background:#02070d!important}html.dark.efp-trick-pdf #pdfCanvas{filter:invert(.965) hue-rotate(180deg) saturate(1.18) brightness(1.12) contrast(1.22)!important;background:#070b12!important}html.dark.efp-trick-pdf .pdf-stage{background:#03070d!important}';document.head.appendChild(clarityStyle);
var focusStyle=document.createElement('style');focusStyle.id='efp-mobile-pdf-clarity';focusStyle.textContent='@media(max-width:820px),(hover:none) and (pointer:coarse) and (max-width:1024px),(hover:none) and (pointer:coarse) and (max-height:1024px) and (max-width:1400px){.reader-head{height:38px!important;min-height:38px!important;padding:3px 6px!important}.reader-shell{height:calc(100dvh - 38px)!important}.reader-title b{font-size:10px!important}.pdf-stage{padding-bottom:66px!important}.pdf-stage canvas{margin:0 auto 6px!important}html.dark #pdfCanvas{filter:invert(.94) hue-rotate(180deg) saturate(1.08) brightness(1.08) contrast(1.14)!important;background:#0a0f18!important}html.dark .pdf-stage{background:#050a12!important}html.dark.efp-book-crux-pdf #pdfCanvas{filter:invert(.965) hue-rotate(180deg) saturate(1.06) brightness(1.13) contrast(1.22)!important;background:#060b12!important}html.dark.efp-book-crux-pdf .pdf-stage{background:#02070d!important}html.dark.efp-economics-crux-pdf #pdfCanvas{filter:invert(.975) hue-rotate(180deg) saturate(1.10) brightness(1.15) contrast(1.25)!important;background:#040910!important}html.dark.efp-economics-crux-pdf .pdf-stage{background:#01060b!important}html.dark.efp-trick-pdf #pdfCanvas{filter:invert(.97) hue-rotate(180deg) saturate(1.22) brightness(1.14) contrast(1.25)!important;background:#060a10!important}html.dark.efp-trick-pdf .pdf-stage{background:#02060b!important}}';document.head.appendChild(focusStyle);
var adaptiveStyle=document.createElement('style');adaptiveStyle.id='efp-pdf-adaptive-profile';adaptiveStyle.textContent='html.dark.efp-trick-pdf.efp-advance-maths-dark-pdf #pdfCanvas{filter:none!important;background:#05070b!important}html.dark.efp-trick-pdf.efp-advance-maths-dark-pdf .pdf-stage{background:#02050a!important}html:not(.dark).efp-advance-maths-dark-pdf #pdfCanvas{filter:invert(.965) hue-rotate(180deg) saturate(1.02) brightness(1.08) contrast(1.14)!important;background:#fff!important}html:not(.dark).efp-advance-maths-dark-pdf .pdf-stage{background:#d9e1ea!important}html.efp-landscape-page.efp-compact-reader .pdf-stage{overflow-y:auto!important}html.efp-landscape-page.efp-compact-reader.efp-auto-fit .pdf-stage{overflow-x:hidden!important}html.efp-mobile-rotated-page .pdf-stage{overflow-y:scroll!important;overflow-x:hidden!important;touch-action:pan-y pinch-zoom!important}html.efp-mobile-rotated-page #pdfCanvas{margin-left:auto!important;margin-right:auto!important}';document.head.appendChild(adaptiveStyle);
function safe(raw,f){try{return JSON.parse(raw)||f}catch(e){return f}}
function bms(){var v=safe(localStorage.getItem('efp_bookmarks'),{});return v&&typeof v==='object'&&!Array.isArray(v)?v:{}}
function saveB(v){try{localStorage.setItem('efp_bookmarks',JSON.stringify(v))}catch(e){}}
function fk(){return 'cruxdoc:'+doc.id}
function pk(){return 'cruxpage:'+doc.id+':'+page}
function prog(){var a=safe(localStorage.getItem('efp_visited_crux_'+doc.id),[]);return Array.isArray(a)?a:[]}
function saveProg(a){try{localStorage.setItem('efp_visited_crux_'+doc.id,JSON.stringify(Array.from(new Set(a))))}catch(e){}}
function recent(){var a=safe(localStorage.getItem('efp_visited_crux_recent'),[]);return Array.isArray(a)?a:[]}
function pushRecent(){var a=recent().filter(function(x){return x!==doc.id});a.unshift(doc.id);a=a.slice(0,20);try{localStorage.setItem('efp_visited_crux_recent',JSON.stringify(a))}catch(e){}}
function toast(s){var t=document.getElementById('toast');t.textContent=s;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(function(){t.classList.remove('show')},1500)}
function markVisited(){var a=prog().filter(function(x){return !/^last:/.test(x)});a.push('p:'+page,'last:'+page);saveProg(a);pushRecent();if(typeof gtag==='function')gtag('event','crux_page_view',{document_id:doc.id,document_title:doc.title,page_number:page,source:doc.source,reader_mode:'pdfjs_original_pdf'})}
function updateUrl(){var p=new URLSearchParams(location.search);p.set('id',doc.id);p.set('page',String(page));history.replaceState(null,'',location.pathname+'?'+p.toString())}
function pdfUrl(){return doc.pdf+'#page='+page+'&zoom=page-width'}
function updateControls(){input.value=page;total.textContent=pdfDoc?pdfDoc.numPages:doc.pages;var b=bms();favBtn.textContent=b[fk()]?'★':'☆';favBtn.classList.toggle('on',!!b[fk()]);bookmarkPage.textContent=b[pk()]?'🔖 Bookmarked':'🔖 Bookmark Page';bookmarkPage.classList.toggle('bookmarked',!!b[pk()]);completeBtn.textContent=prog().indexOf('complete')>=0?'✓ Completed':'✓ Complete';openPdf.href=pdfUrl();openPdf2.href=pdfUrl();zoomLabel.textContent=autoFit?'Fit':Math.round(zoom*100)+'%'}
function showError(msg){pdfLoading.hidden=true;pdfCanvas.hidden=true;pdfError.hidden=false;var p=pdfError.querySelector('p');if(p)p.textContent=msg||'PDF could not be displayed inside the app.'}
function centerMobilePage(){if(!isCompactReader())return;requestAnimationFrame(function(){var left=Math.max(0,(pdfStage.scrollWidth-pdfStage.clientWidth)/2);pdfStage.scrollLeft=left})}
function renderPage(){if(!pdfDoc)return;mobileReader=isCompactReader();document.documentElement.classList.toggle('efp-compact-reader',mobileReader);pdfError.hidden=true;pdfLoading.hidden=false;pdfLoading.textContent='Loading page '+page+'…';pdfCanvas.hidden=true;if(renderTask){try{renderTask.cancel()}catch(e){}renderTask=null}
pdfDoc.getPage(page).then(function(pdfPage){var raw=pdfPage.getViewport({scale:1}),landscape=raw.width>raw.height*1.03,devicePortrait=window.innerHeight>=window.innerWidth,rotateForPortrait=!!(mobileReader&&devicePortrait&&landscape&&autoFit),rotation=((pdfPage.rotate||0)+(rotateForPortrait?90:0))%360,base=pdfPage.getViewport({scale:1,rotation:rotation}),availableW=Math.max(260,pdfStage.clientWidth-(mobileReader?4:18)),stageTop=pdfStage.getBoundingClientRect().top,visibleH=Math.max(220,window.innerHeight-stageTop-(mobileReader?4:18)),widthFit=availableW/base.width,fit=widthFit;lastPageLandscape=landscape;document.documentElement.classList.toggle('efp-landscape-page',landscape);document.documentElement.classList.toggle('efp-portrait-page',!landscape);document.documentElement.classList.toggle('efp-auto-fit',autoFit);document.documentElement.classList.toggle('efp-mobile-rotated-page',rotateForPortrait);if(landscape&&autoFit&&(!mobileReader||!devicePortrait))fit=Math.min(widthFit,visibleH/base.height);var effectiveZoom=autoFit?(landscape?1:zoom):zoom,cssScale=fit*effectiveZoom,dpr=Math.min(window.devicePixelRatio||1,mobileReader?3:2),viewport=pdfPage.getViewport({scale:cssScale*dpr,rotation:rotation}),ctx=pdfCanvas.getContext('2d',{alpha:false});pdfStage.style.overflowY='auto';pdfStage.style.overflowX=(mobileReader&&autoFit)?'hidden':'auto';pdfCanvas.width=Math.floor(viewport.width);pdfCanvas.height=Math.floor(viewport.height);pdfCanvas.style.width=Math.floor(viewport.width/dpr)+'px';pdfCanvas.style.height=Math.floor(viewport.height/dpr)+'px';renderTask=pdfPage.render({canvasContext:ctx,viewport:viewport});return renderTask.promise}).then(function(){renderTask=null;pdfLoading.hidden=true;pdfCanvas.hidden=false;if(mobileReader&&lastPageLandscape&&autoFit)pdfStage.scrollLeft=0;else centerMobilePage();markVisited();updateUrl();updateControls()}).catch(function(err){if(err&&err.name==='RenderingCancelledException')return;showError('This PDF page could not be rendered inside the app.');if(console&&console.error)console.error(err)})}
function go(n){var max=pdfDoc?pdfDoc.numPages:doc.pages;var next=Math.max(1,Math.min(max,n));if(next===page){updateControls();return}page=next;renderPage();pdfStage.scrollTo({top:0,left:isCompactReader()?pdfStage.scrollLeft:0,behavior:'auto'});window.scrollTo({top:0,behavior:'smooth'})}
function loadPdf(){if(!window.pdfjsLib){showError('PDF viewer failed to load. Check your internet connection once, then reopen this page.');return}pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.worker.min.js';pdfLoading.hidden=false;pdfLoading.textContent='Loading original PDF…';pdfjsLib.getDocument({url:doc.pdf}).promise.then(function(loaded){pdfDoc=loaded;total.textContent=loaded.numPages;if(page>loaded.numPages)page=loaded.numPages;renderPage()}).catch(function(err){showError('Original PDF could not be loaded inside the app.');if(console&&console.error)console.error(err)})}
function loadPagesForSearch(){var s=document.createElement('script');s.src='pages/'+doc.id+'.js?v=20260909geoecotricks1';s.onload=function(){pages=Array.isArray(window.EF_CRUX_DOC_PAGES)?window.EF_CRUX_DOC_PAGES:[];runDocSearch()};s.onerror=function(){docSearch.placeholder='PDF search index unavailable — use page number';docSearch.disabled=true};document.head.appendChild(s)}
function runDocSearch(){var q=docSearch.value.trim().toLowerCase();docHits.innerHTML='';if(q.length<2||!pages.length)return;var hits=[];for(var i=0;i<pages.length;i++)if(String(pages[i]).toLowerCase().includes(q))hits.push(i+1);hits.slice(0,30).forEach(function(n){var b=document.createElement('button');b.textContent='Page '+n;b.addEventListener('click',function(){go(n)});docHits.appendChild(b)});if(!hits.length){var s=document.createElement('span');s.textContent='No matching page';docHits.appendChild(s)}else if(hits.length>30){var m=document.createElement('span');m.textContent=' +'+(hits.length-30)+' more';docHits.appendChild(m)}}
title.textContent=doc.title;crumb.textContent=doc.breadcrumb+' · '+doc.pages+' pages';document.title=doc.title+' | Original PDF | ExamFusion Prep';
document.getElementById('backBtn').addEventListener('click',function(){if(history.length>1)history.back();else location.href='index.html'});
document.getElementById('prev').addEventListener('click',function(){go(page-1)});
document.getElementById('next').addEventListener('click',function(){go(page+1)});
input.addEventListener('change',function(){go(parseInt(input.value,10)||page)});
input.addEventListener('keydown',function(e){if(e.key==='Enter'){e.preventDefault();go(parseInt(input.value,10)||page);input.blur()}});
document.getElementById('zoomIn').addEventListener('click',function(){mobileReader=isCompactReader();if(autoFit&&lastPageLandscape)zoom=1;autoFit=false;var step=mobileReader?0.10:0.25;zoom=Math.min(2.5,Math.round((zoom+step)*100)/100);updateControls();renderPage()});
document.getElementById('zoomOut').addEventListener('click',function(){mobileReader=isCompactReader();if(autoFit&&lastPageLandscape)zoom=1;autoFit=false;var step=mobileReader?0.10:0.25;zoom=Math.max(.75,Math.round((zoom-step)*100)/100);updateControls();renderPage()});
favBtn.addEventListener('click',function(){var b=bms();if(b[fk()])delete b[fk()];else b[fk()]=true;saveB(b);updateControls();toast(b[fk()]?'Added to favourites':'Removed from favourites')});
bookmarkPage.addEventListener('click',function(){var b=bms();if(b[pk()])delete b[pk()];else b[pk()]=true;saveB(b);updateControls();toast(b[pk()]?'Page bookmarked · Open My Pages to view it':'Page bookmark removed')});
completeBtn.addEventListener('click',function(){var a=prog(),i=a.indexOf('complete');if(i>=0){saveProg([]);updateControls();toast('Completion removed · Progress reset to 0%')}else{var max=pdfDoc?pdfDoc.numPages:doc.pages,done=['complete'];for(var n=1;n<=max;n++)done.push('p:'+n);done.push('last:'+page);saveProg(done);updateControls();toast('Marked complete · Progress 100%')}});
if(resetProgressBtn)resetProgressBtn.addEventListener('click',function(){if(!window.confirm('Reset reading progress for this PDF?\n\nBookmarks and favourites will stay saved.'))return;saveProg([]);updateControls();toast('Reading progress reset to 0%');if(typeof gtag==='function')gtag('event','crux_progress_reset',{document_id:doc.id,document_title:doc.title,source:doc.source})});
var st;docSearch.addEventListener('input',function(){clearTimeout(st);st=setTimeout(runDocSearch,140)});
var resizeTimer;function refitForViewport(forceFit){clearTimeout(resizeTimer);resizeTimer=setTimeout(function(){var portrait=window.innerHeight>=window.innerWidth,changed=portrait!==lastDevicePortrait;mobileReader=isCompactReader();lastDevicePortrait=portrait;if(forceFit||changed){autoFit=true;zoom=mobileReader?1.10:1}if(pdfDoc&&!document.body.classList.contains('mobile-tools-open')){updateControls();renderPage()}},180)}window.addEventListener('resize',function(){refitForViewport(false)});window.addEventListener('orientationchange',function(){refitForViewport(true)});if(window.visualViewport)window.visualViewport.addEventListener('resize',function(){refitForViewport(false)});if(window.screen&&screen.orientation&&screen.orientation.addEventListener)screen.orientation.addEventListener('change',function(){refitForViewport(true)});
function dark(){document.documentElement.classList.toggle('dark',localStorage.getItem('efp_black_mode')==='on');document.getElementById('darkBtn').textContent=document.documentElement.classList.contains('dark')?'Light':'Dark'}
document.getElementById('darkBtn').addEventListener('click',function(){localStorage.setItem('efp_black_mode',document.documentElement.classList.contains('dark')?'off':'on');dark()});
dark();updateControls();loadPdf();loadPagesForSearch();
})();
